export const colors = {
  yellow: "#f4e85eff",
  lime: "#d4e157",
  green: "#b9ef7aff",
  teal: "#8cf7deff",
  blue: "#a7e3f1ff",
  darkblue: "#aecbfa",
  indigo: "#9fa8da",
  purple: "#d7aefb",
  lavender: "#e1bee7",
  rose: "#f8bbd0",
  pink: "#fdcfe8",
  beige: "#ffe0b2",
  brown: "#e6c9a8",
  amber: "#ffd54f",
  orange: "#fbbc04",
  coral: "#ff9e80",
  red: "#f28b82",
  default: "#ffffff",
};
