import type { NoteType } from "../types";
import { colors } from "./colors";

export const initialNotes: NoteType[] = [
  {
    id: "1",
    title: "Shopping List",
    content: "",
    color: colors.yellow,
    isPinned: true,
    isArchived: false,
    updatedAt: new Date(),
    isCheckboxNote: true,
    checkboxItems: [
      { id: "c1", text: "1000 liters of Milk", checked: false },
      { id: "c2", text: "1 Kamelåså", checked: true },
      { id: "c3", text: "3 Spig snigel", checked: false },
      { id: "c4", text: "2kg butter", checked: false },
    ],
  },
  {
    id: "2",
    title: "Meeting Notes",
    content: "Discuss project timeline  Assign tasks   Set next meeting",
    color: colors.green,
    isPinned: false,
    isArchived: false,
    updatedAt: new Date(),
  },
  {
    id: "3",
    title: "Ideas for Weekend",
    content: "Visit the park Try new restaurant Watch a movie",
    color: colors.blue,
    isPinned: false,
    isArchived: false,
    updatedAt: new Date(),
  },
  {
    id: "4",
    title: "Book Recommendations",
    content:
      "The Alchemist by Paulo Coelho Atomic Habits by James Clear Project Hail Mary by Andy Weir",
    color: colors.purple,
    isPinned: false,
    isArchived: false,
    updatedAt: new Date(),
  },
  {
    id: "5",
    title: "Vacation ideas",
    content: "Visit the beach. Explore the mountains. City tour.",
    color: colors.brown,
    isPinned: true,
    isArchived: false,
    updatedAt: new Date(),
  },
  {
    id: "6",
    title: "Workout Plan",
    content: "10 000 squats of 100kg every single day",
    color: colors.orange,
    isPinned: false,
    isArchived: true,
    updatedAt: new Date(),
    isCheckboxNote: false,
  },
  {
    id: "7",
    title: "Life Goals",
    content: "",
    color: colors.teal,
    isPinned: false,
    isArchived: true,
    updatedAt: new Date(),
    isCheckboxNote: true,
    checkboxItems: [
      { id: "c1", text: "Eat pizza", checked: true },
      { id: "c2", text: "Eat 1 Kamelåså", checked: true },
      { id: "c3", text: "Watch 3 Spig snigel grow", checked: false },
      { id: "c4", text: "Eat 2kg butter", checked: false },
    ],
  },
];
